name: Lip Reading CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install pip
      run: |
        Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
        python get-pip.py --force-reinstall
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
        # You might need additional setup steps for your environment

    - name: Run lip reading script
      run: python your_script.py
